---

repo_url: https://github.com/Projetos-de-Extensao/PBE_25.2_8001_I
repo_name: PBE_25.2_8001_I
site_author: Jonh Carvalho
site_name: Quinto Elemento
nav: 
  - Home: index.md
  - Iniciação: 
      - Pesquisa: Iniciacao/pesquisa.md
      - Index: Iniciacao/index.md
      - Design Thinking: Iniciacao/design_thinking.md
      - Brainstorming: Iniciacao/Brainstorm.md
      - 5w2h: Iniciacao/5w2h.md
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Metodologia Ágil: Iniciacao/metodologia.md
      - Prototipagem Baixa Fidelidade: Iniciacao/prototipo_baixa_fidelidade.md

  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/das.md
      - Casos de Uso: Elaboracao/casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Diagrama de Sequência: Elaboracao/diagrama_de_sequencia.md
      - Protótipo de Alta Fidelidade: Elaboracao/prototipo_alta_fidelidade.md
  - Construção:
      - Index: Construcao/index.md
      - Git Issues: Construcao/git_issues.md
      - GitHub Projects: Construcao/github_projects.md
      - CodeSpace: Construcao/codespace.md
  - Sobre o Projeto:
      - Index: Sobre o Projeto/index.md
      - Integrantes: Sobre o Projeto/integrantes.md
      

extra_css:
  - css/extra.css


markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables

  - toc:
      permalink: true

plugins:
  - minify:
      minify_html: true
  - search
  

  



theme:
  name: material
  logo: assets/explosaum.gif
  palette:
    # Tema claro
    - scheme: default
      primary: 
      accent: 
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    # Tema escuro
    - scheme: slate
      primary:
      accent: 
      toggle:
        icon: material/white-balance-sunny   
        name: Mudar para modo claro



  
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Open Sans
    code: 
  icon:
    repo: material/cat
    logo: simple/react
    favicon: simple/react
  

   
    