@startuml
:Aluno: --> (Registrar-se na plataforma)
:Aluno: --> (Autenticar-se)
:Aluno: --> (Editar perfil)
:Aluno: --> (Navegar disciplinas)
:Aluno: --> (Candidatar-se à vaga)
:Aluno: --> (Agendar atendimento)
:Aluno: --> (Trocar mensagens)
:Aluno: --> (Avaliar monitoria)
:Aluno: --> (Receber notificações)
:Aluno: --> (Consultar regulamentos)

:Monitor: --> (Registrar-se na plataforma)
:Monitor: --> (Autenticar-se)
:Monitor: --> (Editar perfil)
:Monitor: --> (Navegar disciplinas)
:Monitor: --> (Publicar agenda)
:Monitor: --> (Trocar mensagens)
:Monitor: --> (Receber notificações)
:Monitor: --> (Consultar regulamentos)

:Professor: --> (Registrar-se na plataforma)
:Professor: --> (Autenticar-se)
:Professor: --> (Editar perfil)
:Professor: --> (Navegar disciplinas)
:Professor: --> (Abrir vaga de monitoria)
:Professor: --> (Selecionar monitores)
:Professor: --> (Vincular monitor)
:Professor: --> (Trocar mensagens)
:Professor: --> (Avaliar monitoria)
:Professor: --> (Receber notificações)
:Professor: --> (Consultar regulamentos)
:Professor: --> (Relatórios por disciplina)

"Admin Principal" as Admin
Admin --> (Validar professor)
Admin --> (Vincular monitor)
Admin --> (Moderar conteúdo)
Admin --> (Gerenciar políticas)
@enduml
