# Generated by Django 5.2.7 on 2025-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_vagamonitoria_delete_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagamonitoria',
            old_name='descricao',
            new_name='prerequisitos',
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='numero_vagas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='responsabilidades',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]