# Generated by Django 5.2.7 on 2025-11-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_rename_descricao_vagamonitoria_prerequisitos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.CharField(max_length=100)),
                ('historico_escolar', models.FileField(upload_to='documentos/')),
                ('curriculo', models.FileField(upload_to='documentos/')),
                ('carta_motivacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.vagamonitoria')),
            ],
        ),
    ]
