# Generated by Django 5.2.7 on 2025-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_candidato_candidatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagamonitoria',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
