# Generated by Django 5.2.7 on 2025-11-06 01:32

import re
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _get_user_model(apps):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    return apps.get_model(app_label, model_name)


def _sanitize_codigo(nome: str) -> str:
    base = re.sub(r'[^A-Z0-9]+', '-', (nome or '').upper()).strip('-')
    return base[:20] if base else ''


def migrate_vagas_forward(apps, schema_editor):
    Departamento = apps.get_model('content_app', 'Departamento')
    Disciplina = apps.get_model('content_app', 'Disciplina')
    Vaga = apps.get_model('content_app', 'VagaMonitoria')
    User = _get_user_model(apps)

    default_departamento, _ = Departamento.objects.get_or_create(
        sigla='GER',
        defaults={'nome': 'Departamento Geral', 'descricao': 'Departamento padrão gerado na migração.'},
    )

    coordenador_fallback = User.objects.filter(is_superuser=True).order_by('id').first()
    if coordenador_fallback is None:
        coordenador_fallback = User.objects.filter(is_staff=True).order_by('id').first()

    for vaga in Vaga.objects.all():
        disciplina_nome = getattr(vaga, 'disciplina_legada', None) or 'Disciplina Não Informada'
        codigo_base = _sanitize_codigo(disciplina_nome)
        if not codigo_base:
            codigo_base = f'DISC-{vaga.pk}'

        codigo = codigo_base
        sufixo = 1
        while Disciplina.objects.filter(codigo=codigo).exists():
            sufixo += 1
            codigo = f"{codigo_base[:16]}-{sufixo}"[:20]

        coordenador = getattr(vaga, 'criado_por', None) or coordenador_fallback
        if coordenador is None:
            coordenador = User.objects.order_by('id').first()

        disciplina = Disciplina.objects.filter(nome=disciplina_nome, departamento=default_departamento).first()
        if disciplina is None:
            disciplina = Disciplina.objects.create(
                nome=disciplina_nome,
                codigo=codigo,
                departamento=default_departamento,
                carga_horaria=60,
                periodo='Indefinido',
                semestre='Indefinido',
                coordenador=coordenador,
            )

        vaga.disciplina_id = disciplina.id
        if vaga.criado_por is None and coordenador is not None:
            vaga.criado_por_id = coordenador.id
        vaga.save(update_fields=['disciplina', 'criado_por'])


def migrate_vagas_backward(apps, schema_editor):
    Vaga = apps.get_model('content_app', 'VagaMonitoria')
    for vaga in Vaga.objects.all():
        disciplina = getattr(vaga, 'disciplina', None)
        if disciplina is not None:
            vaga.disciplina_legada = disciplina.nome
            vaga.save(update_fields=['disciplina_legada'])


def seed_permission_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for nome in ['Admin', 'Coordenador', 'Estudante']:
        Group.objects.get_or_create(name=nome)


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_alter_vagamonitoria_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=16, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='candidato',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='candidatura',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vagamonitoria',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vaga de Monitoria', 'verbose_name_plural': 'Vagas de Monitoria'},
        ),
        migrations.RenameField(
            model_name='vagamonitoria',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='candidatura',
            old_name='data_candidatura',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vagamonitoria',
            old_name='disponivel',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='vagamonitoria',
            old_name='numero_vagas',
            new_name='quantidade_vagas',
        ),
        migrations.RenameField(
            model_name='vagamonitoria',
            old_name='professor',
            new_name='criado_por',
        ),
        migrations.AddField(
            model_name='candidato',
            name='cr_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
        migrations.AddField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='periodo_atual',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetida'), ('in_review', 'Em Análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='ultima_atualizacao_status',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='bolsa_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='carga_horaria_semanal',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='cr_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))]),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='inscricoes_fim',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='inscricoes_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='monitoria_fim',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='monitoria_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='periodo_minimo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='permitir_edicao_submetida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('under_review', 'Em Avaliação'), ('closed', 'Finalizada')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='carta_motivacao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='historico_escolar',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='content_app.candidato'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='content_app.vagamonitoria'),
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='prerequisitos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='responsabilidades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='quantidade_vagas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('candidato', 'vaga')},
        ),
        migrations.RenameField('vagamonitoria', 'disciplina', 'disciplina_legada'),
        migrations.CreateModel(
            name='AuditoriaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carga_horaria', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('periodo', models.CharField(max_length=30)),
                ('semestre', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_coordenadas', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='content_app.departamento')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('nome', 'departamento', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='vagamonitoria',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='content_app.disciplina'),
        ),
        migrations.RunPython(migrate_vagas_forward, migrate_vagas_backward),
        migrations.RunPython(seed_permission_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vagamonitoria',
            name='disciplina_legada',
        ),
        migrations.AlterField(
            model_name='vagamonitoria',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vagas', to='content_app.disciplina'),
        ),
    ]
