# Generated by Django 5.2.7 on 2025-11-13 02:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_drop_candidato_embed_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submetida'), ('in_review', 'Em Análise'), ('approved', 'Aprovada'), ('waitlist', 'Lista de Espera'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='AvaliacaoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Nota da avaliação (0 a 10)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('criterios_avaliacao', models.JSONField(blank=True, default=dict, help_text='Critérios específicos avaliados (ex: conhecimento técnico, motivação, etc)')),
                ('comentarios', models.TextField(blank=True, help_text='Comentários e observações sobre o candidato')),
                ('resultado', models.CharField(blank=True, choices=[('approved', 'Aprovado'), ('waitlist', 'Lista de Espera'), ('rejected', 'Reprovado')], help_text='Resultado final da seleção', max_length=20, null=True)),
                ('mensagem_resultado', models.TextField(blank=True, help_text='Mensagem padronizada a ser enviada ao candidato')),
                ('resultado_comunicado', models.BooleanField(default=False, help_text='Indica se o resultado já foi comunicado ao candidato')),
                ('data_comunicacao', models.DateTimeField(blank=True, help_text='Data em que o resultado foi comunicado', null=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='content_app.candidatura')),
            ],
            options={
                'verbose_name': 'Avaliação de Candidato',
                'verbose_name_plural': 'Avaliações de Candidatos',
                'ordering': ['-created_at'],
                'unique_together': {('candidatura', 'avaliador')},
            },
        ),
    ]
