# Generated by Django 5.2.7 on 2025-11-14 02:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('carga_horaria_semanal', models.PositiveSmallIntegerField(help_text='Horas semanais previstas', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('afastado', 'Afastado'), ('desligado', 'Desligado'), ('concluido', 'Concluído')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to='content_app.candidatura')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário do sistema (se tiver cadastro)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitorias', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitores', to='content_app.vagamonitoria')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'ordering': ['-created_at'],
                'unique_together': {('vaga', 'candidatura')},
            },
        ),
        migrations.CreateModel(
            name='RegistroFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('reposicao', 'Reposição'), ('extra', 'Extra')], default='normal', max_length=20)),
                ('atividades', models.TextField(blank=True, help_text='Descrição das atividades realizadas')),
                ('local', models.CharField(blank=True, help_text='Local onde a monitoria foi realizada', max_length=100)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='content_app.monitor')),
                ('validado_por', models.ForeignKey(blank=True, help_text='Professor que validou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Frequência',
                'verbose_name_plural': 'Registros de Frequência',
                'ordering': ['-data', '-entrada'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField()),
                ('total_horas', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6)),
                ('dias_trabalhados', models.PositiveSmallIntegerField(default=0)),
                ('carga_horaria_prevista', models.DecimalField(decimal_places=2, help_text='Carga horária mensal esperada', max_digits=6)),
                ('percentual_cumprido', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Percentual da carga horária cumprida', max_digits=5)),
                ('resumo_atividades', models.TextField(blank=True)),
                ('observacoes_professor', models.TextField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_aprovados', to=settings.AUTH_USER_MODEL)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='content_app.monitor')),
            ],
            options={
                'verbose_name': 'Relatório Mensal',
                'verbose_name_plural': 'Relatórios Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('monitor', 'mes', 'ano')},
            },
        ),
    ]
